### ISSUE TITLE
allowed option

### ISSUE THREAD

**Issue by badulesia** [ssbeefeater/ssi-uploader#1]
Hello.
A weird behavior with the allowed option : it seems to accept png file whatever allowed option is set.
for example :
`allowed: ['pdf']`
It refuses any file except pdf, as expected, but it still accepts png files while they should be refused.
I've done tests with several extensions (docx, txt, sql ...) and the issue still the same.
Can you check this please ?

**Comment by ssbeefeater** [comment]
You are right! This was a bug ! Thank you for mentioning it. I fixed and
ready!

2016-07-12 14:10 GMT+03:00 badulesia <notifications@github.com>:

**Comment by badulesia** [comment]
Le 12/07/2016 à 16:27, Mike a écrit :
> You are right! This was a bug ! Thank you for mentioning it. I fixed and
> ready!
>
This also happens with gif file.
It bugged me half an hour this morning. As now I have only use the 
plugin for what it does (well !), now I'm trying error control.
Thank you :)
