### ISSUE TITLE
Can't upload image more than 2Mb

### ISSUE THREAD

**Issue by chinhnm** [ssbeefeater/ssi-uploader#11]
post_max_size = 100M
upload_max_filesize = 100M
I change it in php.ini but it doesn't work, i use other plugin in same site upload more than 2mb it works perfect. Can you please check it. I really need help.

**Comment by ssbeefeater** [comment]
By default the max upload size in ssi-uploader is 2mb. You xan change it using tha maxFileSize option

```javascript
$('#ssi-uploader').ssi_uploader({
   maxFileSize: 100   //mb
});

```

**Comment by chinhnm** [comment]
First thank you for answer me, i just change it before but it did't work.
$('#ssi-upload').ssi_uploader({
    url: uploadImage_url,
    maxFileSize: 100,
    allowed: ['jpg', 'jpeg', 'png', 'svg']
    ,onEachUpload:function(file){console.log(file)}
});
console.log return 500 (Internal Server Error).

**Comment by ssbeefeater** [comment]
that means there is an error on the server side, nothing to do with the ssi-uploader plugin

**Comment by chinhnm** [comment]
Thank your answer, have a good day!
