### ISSUE TITLE
Request : style name change to avoid interference with other plugin

### ISSUE THREAD

**Issue by badulesia** [ssbeefeater/ssi-uploader#2]
Hello.
A tiny request.
There is a style named ".selected". This name is too simple and interfers with other plugins I use. Furthermore ssi-uploader styles are prefixed with ssi-, which is logic, except for ".selected".
So my request is to rename the style ".selected" into ".ssi-selected", and modify the js code as needed.
I should be easy to do :)
Thank you.

**Comment by ssbeefeater** [comment]
This css rule is unnecessary. Propably i forgot to remove it from css file. I'll push the changes. Thank you!

**Comment by badulesia** [comment]
Le 21/07/2016 à 14:01, Mike a écrit :
> This css rule is unnecessary. Propably i forgot to remove it from css
> file. I'll push the changes. Thank you!
>
Hello.
I checked the js code and found no reference to this style, so it seemed 
strange. I assumed it was some remain from a previous episode of 
development, so I deleted it by my own. Your answer goes in the same 
direction.
Thank you.
