### ISSUE TITLE
maybe you should add type="button" attribute for every button

### ISSUE THREAD

**Issue by mengkeys** [ssbeefeater/ssi-uploader#4]
I have use it in bootstrap modal and inner form , when I click the button "choose file", the modal has be closed.

**Comment by ssbeefeater** [comment]
i check this, but i dont have the same behavor. Everything looks fine. [See here](http://codepen.io/ssbeefeater/pen/PGrBBB)

**Comment by mengkeys** [comment]
@ssbeefeater I click choose file button, the form has be submit, then, current page has be relaod, so , modal has be closed.

**Comment by ssbeefeater** [comment]
I see now. It's easy fix.
