### ISSUE TITLE
problem about callback.response

### ISSUE THREAD

**Issue by wangkai1994** [ssbeefeater/ssi-uploader#5]
callback.responseMsg is null when response type is json ?

**Comment by wangkai1994** [comment]
btw: 
```
//structure 2
$('#ss-uploader').ssi_uploader({
  responseValidation:{
    validationKey: {
      success: 'success',
      error: 'actionError'
    },
    resultKey: 'validationKey'
  }
})

```
I don't know how it works,i return json like {"actionError":"hasActionError","success":"success"} but it dosn't work?
problem like:
Cannot read property 'hasOwnProperty' of null  in "data.hasOwnProperty(valData.validationKey.success"
 forgive my poor English = =.

**Comment by ssbeefeater** [comment]
@wangkai1994 Thanks for the report! As now, the ssi-uploader didn't display messages, if the response was successful but this was changed in the 1.3.1 version. To understand better how responseValidation property works, you can see [these](http://ssbeefeater.github.io/#ssi-uploader/documentation/3) examples.

**Comment by ssbeefeater** [comment]
@wangkai1994 To be more clear, see this image. 

![enter image description here][1]



  [1]: https://s17.postimg.org/v60nb5ab3/Untitled.png

**Comment by wangkai1994** [comment]
THANK YOU FOR YOUR ANSWER bro! btw, i think $.parseJSON should be replaced by JSON.stringify?$.parseJSON can not parse response which type is jsonObject? I use JSON.stringify and it works.
