### ISSUE TITLE
new bug when delete picture

### ISSUE THREAD

**Issue by wangkai1994** [ssbeefeater/ssi-uploader#6]
1.select 2 files 
2.click red delete button under the first file
3.select files again  then you will see first file has been changed.

**Comment by ssbeefeater** [comment]
Thanks for the report. I'll check and fix it later!

**Comment by wangkai1994** [comment]
Hey Mike! I am waiting for you fix this bug.Thanks!

**Comment by ssbeefeater** [comment]
@wangkai1994  Thank you for reminding me this.
